config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles-store
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: true
  workdir: ~/.config/dotdrop
dotfiles:
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_bash_envvars:
    src: bash_envvars
    dst: ~/.bash_envvars
  f_bash_aliases:
    src: bash_aliases
    dst: ~/.bash_aliases
  f_bash_functions:
    src: bash_functions
    dst: ~/.bash_functions
  f_profile:
    src: profile
    dst: ~/.profile
  f_bash_logout:
    src: bash_logout
    dst: ~/.bash_logout
  f_install_script.sh:
    src: install_script.sh
    dst: ~/install_script.sh
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_ideavimrc:
    src: ideavimrc
    dst: ~/.ideavimrc
  f_vim_colors_solarized.vim:
    src: vim/colors/solarized.vim
    dst: ~/.vim/colors/solarized.vim
profiles:
  worklaptop:
    dotfiles:
    - f_gitconfig
    - f_bashrc
    - f_bash_envvars
    - f_bash_aliases
    - f_bash_functions
    - f_profile
    - f_bash_logout
    - f_install_script.sh
    - f_vimrc
    - f_ideavimrc
    - f_vim_colors_solarized.vim
  homelaptop:
    dotfiles:
    - f_gitconfig
    - f_profile
    - f_bash_logout
    - f_install_script.sh
    - f_vimrc
    - f_ideavimrc
