config:
  backup: true
  banner: false
  create: true
  diff_command: icdiff -N --no-bold -U 3 {1} {0}
  dotpath: dotfiles-global-store
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: true
  showdiff: true
  workdir: ~/.config/dotdrop-global
dotfiles:
  f_etc_docker_daemon.json:
    src: etc/docker/daemon.json
    dst: /etc/docker/daemon.json
  f_etc_sysctl.d_60-idea.conf:
    src: etc/sysctl.d/60-idea.conf
    dst: /etc/sysctl.d/60-idea.conf
profiles:
  base:
    dotfiles:
    - f_etc_docker_daemon.json
    - f_etc_sysctl.d_60-idea.conf
  worklaptop:
    include:
    - base 
  workremote:
    dotfiles:
  rpiremote:
    dotfiles:
  homelaptop:
    dotfiles:
