config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles-store
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: true
  workdir: ~/.config/dotdrop
dotfiles:
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_bash_envvars:
    src: bash_envvars
    dst: ~/.bash_envvars
  f_bash_aliases:
    src: bash_aliases
    dst: ~/.bash_aliases
  f_bash_functions:
    src: bash_functions
    dst: ~/.bash_functions
profiles:
  worklaptop:
    dotfiles:
    - f_gitconfig
    - f_bashrc
    - f_bash_envvars
    - f_bash_aliases
    - f_bash_functions
