" Remap keys for a more ergonomic hand placement on the keyboard
noremap ; l
noremap l k
noremap k j
noremap j h
set laststatus=2
python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup
