"
" Vim configuration file
"

" Common Configuration
set number
set numberwidth=4
set ignorecase smartcase

" Set tab settings
set tabstop=2
set shiftwidth=2
set expandtab
    
" Navigation Configuration
" Normal Model navigation keys for ergonomic hand placement
noremap ; l
noremap l k
noremap k j
noremap j h


" Visual Configuration
" Download first curl -fLo ~/.vim/colors/solarized.vim --create-dirs https://raw.githubusercontent.com/ericbn/vim-solarized/master/colors/solarized.vim
set background=dark
colorscheme solarized
syntax on
syntax enable

" Powerline setup
set laststatus=2
python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup

