"
" Vim configuration file
"

" Common Configuration
set number                                " Shows line numbers in left gutter
set numberwidth=4                         " Gutter width for numbers
set ignorecase smartcase                  " Case insensetive search; but becomes case sensetive if there is an upper case letter in search term
set modeline                              " Enable modeline to process # vim: filetype=sh etc.... settings when opening files


" Set tab settings
set tabstop=2
set shiftwidth=2
set expandtab
    
" Navigation Configuration
" Normal Model navigation keys for ergonomic hand placement
noremap ; l
noremap l k
noremap k j
noremap j h


" Visual Configuration
" Download first curl -fLo ~/.vim/colors/solarized.vim --create-dirs https://raw.githubusercontent.com/ericbn/vim-solarized/master/colors/solarized.vim
set term=screen-256color
set background=dark
colorscheme solarized
syntax on
syntax enable

" Powerline setup
set laststatus=2
python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup

